-- Lucky's Wardrobe: the bundled set data the Extra Sets tab is built from.
-- Generated by tools/generate_extra_sets_data.py; do not edit by hand.
--
-- The client holds every one of these sets in its own data, but only lists a
-- fraction of them through C_TransmogSets.GetAllSets. The bundled snapshot
-- names the rest; everything else about them is read live from the client.
LuckysWardrobe = LuckysWardrobe or {}

LuckysWardrobe.ExtraSetsData = {
    snapshot = "2026-08-04",
    -- armorType values are the client's own armour subclass IDs.
    armorTypes = {
        { key = "cloth", armorType = 1 },
        { key = "leather", armorType = 2 },
        { key = "mail", armorType = 3 },
        { key = "plate", armorType = 4 },
    },
    sets = {},
}
